### ISSUE TITLE
NVIDIA/COSMOFLOW , Pre-processing Datasets Scaling Issue

### ISSUE THREAD

**Issue by karanveersingh5623** [mlcommons/hpc_results_v1.0#3]
Hi Team

Do we need GPU dependency for pre-processing dataset ? If no , how can we by-pass it ?
Running below cmd uses 80GB of GPU Memory ( A100s)
`docker run --rm -it --ipc=host --gpus device=0 -v /mnt/lustre:/mnt cosmoflow-nvidia:0.4 bash -c 'cd tools/ && python3 convert_tfrecord_to_numpy.py -i /mnt/cosmoUniverse_2019_05_4parE_tf_v2/train -o /mnt/processed/train -c GZIP -p 1000'`
 
- Not using slurm for pre-processing as of now , just doing basic way.
- Divided train dataset (1.4 TB) into 16 folders ,  each folder (100GB approx).
- Has 4 X A100s GPUs in single Dell R750XA server
- Tried running 16 Containers , 4Cs / GPU--> Fail , Max = 2Cs/GPU
- GPU Core utilization is very low 4% , Memory is fully utilized 
How can I bypass this condition , I want to divide and run multiple containers to pre-process the dataset fast and want to increase IOs on lustre filesystem backed by NVMes ?

**Comment by karanveersingh5623** [comment]
-p 1 also shows the same memory and core utilization

**Comment by karanveersingh5623** [comment]
Commented out the GPU code block in convert_tfrecord_to_numpy.py , closing the issue

**Comment by karanveersingh5623** [comment]
Reopening the issue , the change works fine and I can see data being processed but it fails after sometime . Below is the trace .
**Note - No GPU being used 
```
root@8df72c4faced:/workspace/cosmoflow/tools# python3 convert_tfrecord_to_numpy.py -i /mnt/cosmoUniverse_2019_05_4parE_tf_v2/train/1 -o /mnt/processed/train/1 -c GZIP -p 100
Found 131072 files, 0 are done, 131072 are remaining.
2022-04-30 06:45:45.632724: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib
2022-04-30 06:45:45.632751: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-30 06:45:45.632768: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2022-04-30 06:45:45.633122: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Traceback (most recent call last):
  File "convert_tfrecord_to_numpy.py", line 110, in <module>
    main()
  File "convert_tfrecord_to_numpy.py", line 103, in main
    convert_numpy(record, ofname_data, ofname_label)
  File "convert_tfrecord_to_numpy.py", line 51, in convert_numpy
    np.save(ofname_data, data_arr)
  File "<__array_function__ internals>", line 180, in save
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 519, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/format.py", line 690, in write_array
    array.tofile(fp)
OSError: 8388608 requested and 0 written
```

**Comment by karanveersingh5623** [comment]
When I attached the GPU to docker run command and hashed out the GPU code block , its still using the GPU memory .
Please refer the screenshot .
![A100s-cosmoflow](https://user-images.githubusercontent.com/30921663/166095685-2cf0477b-ff5a-49c3-962a-660521154deb.PNG)

**Comment by karanveersingh5623** [comment]
Hi Team 

Anyone can update on the above query ???

**Comment by hXl3s** [comment]
I think it is related to stupidity of Tensorflow. By default, preprocessing code should not be running anything on GPU but needs TF to read tfrecords data (orginal dataset) and convert it to numpy arrays (format used by NVIDIA implementation). Tensorflow by default, seeing GPU is allocating all the memory and there is nothing that can be done about that I think. Workaround would be to use Tensorflow not compiled with GPU support (so CPU only), to avoid GPU allocation.

Please remember, that preprocessing has to be done once, you can save result into persistent storage compliant with MLPerf rules and use it as it is

**Comment by karanveersingh5623** [comment]
@hXl3s 
I made Nvidia 2-Nodes Deepops cluster to run sbatch cmds mentioned in this repo .
Trying the below cmd , gives this error trace . Seems like issue with container entrypoint 

```
# sbatch -N 1 init_datasets.sub
Submitted batch job 10
```

```
pyxis: importing docker image ...
dpkg: warning: version '4.18.0-348.7.1.el8_5.x86_64' has bad syntax: invalid character in revision number
/usr/bin/bash: tools/init_datasets.sh: No such file or directory
srun: error: mlperf1: task 0: Exited with exit code 127 
```

**Comment by karanveersingh5623** [comment]
@hXl3s 

Two Questions 

1. How we are getting this directory [ NVIDIA/benchmarks/cosmoflow/implementations/mxnet ] as work directory inside this docker container --> {nvcr.io/nvidia/tensorflow:21.09-tf1-py3 } ?

2. How we are mounting Data Source & Data Destination directories inside the pyxis enabled enroot container ?

```
#!/bin/bash
#SBATCH --job-name mlperf-hpc:cosmoflow_data

: "${DATA_SRC_DIR:?DATA_SRC_DIR not set}"
: "${DATA_DST_DIR:?DATA_DST_DIR not set}"

readonly _container="nvcr.io/nvidia/tensorflow:21.09-tf1-py3"
readonly _cont_name="cosmoflow-preprocess"

srun --ntasks="$(( SLURM_JOB_NUM_NODES * 16 ))" --container-image="${_container}" --container-name="${_cont_name}" \
    bash tools/init_datasets.sh
```

**Comment by karanveersingh5623** [comment]
@hXl3s 
I tried adding mount options in SRUN cmd , below is the trace , the nvidia tensorflow image gives the dependencies error .
Should I create my own image or do we have some public image which handles this scenario ?

```
srun --ntasks=1 --container-image=nvcr.io#nvidia/tensorflow:22.05-tf1-py3 --container-name=cosmoflow-preprocess --container-workdir=/mnt/ --container-mounts=/root/hpc_results_v1.0/NVIDIA/benchmarks/cosmoflow/implementations/mxnet:/mnt bash tools/init_datasets.sh /mnt/cosmoUniverse_2019_05_4parE_tf_small /mnt/processed


pyxis: importing docker image ...
2022-06-29 01:18:38.954846: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/mnt/tools/convert_tfrecord_to_numpy.py", line 8, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
2022-06-29 01:18:40.133354: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/mnt/tools/convert_tfrecord_to_numpy.py", line 8, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
tools/init_datasets.sh: line 6: /root/deepops/processed/train/files_data.lst: No such file or directory
ls: cannot access '/root/deepops/processed/train': No such file or directory
tools/init_datasets.sh: line 7: /root/deepops/processed/validation/files_data.lst: No such file or directory
ls: cannot access '/root/deepops/processed/validation': No such file or directory
tools/init_datasets.sh: line 8: /root/deepops/processed/train/files_label.lst: No such file or directory
ls: cannot access '/root/deepops/processed/train': No such file or directory
tools/init_datasets.sh: line 9: /root/deepops/processed/validation/files_label.lst: No such file or directory
ls: cannot access '/root/deepops/processed/validation': No such file or directory
srun: error: mlperf1: task 0: Exited with exit code 1
```

**Comment by karanveersingh5623** [comment]
@hXl3s , is anyone supporting this repo or its EOL ?
