### ISSUE TITLE
Slurm GPU cluster failing to run pre-processing on more than 1 node

### ISSUE THREAD

**Issue by karanveersingh5623** [mlcommons/hpc_results_v1.0#4]
Hi Team

I created Nvidia Deepops 2-Node cluster with Dell R750 using Nvidia A100s GPUs .
When trying to run data preprocessing using 2 Nodes + 2GPUS + 2 tasks , the task fails with some UCX errors .

Below is the trace, please refer - 

```
(env) [root@hpc-master ~]# srun -N 2 -G 2 --ntasks=2 --container-image=192.168.61.4:5000#/cosmoflow-nvidia:0.4 --container-name=cosmoflow-preprocess --container-workdir=/mnt/ --contanet:/mnt bash /mnt/tools/init_datasets.sh


dpkg: warning: version '4.18.0-348.el8.x86_64' has bad syntax: invalid character in revision number
dpkg: warning: version '4.18.0-348.7.1.el8_5.x86_64' has bad syntax: invalid character in revision number
[1657786922.147458] [mlperf1:1207478:0]            sock.c:260  UCX  ERROR   connect(fd=41, dest_addr=172.17.0.1:45031) failed: Connection refused
[mlperf1:1207478] pml_ucx.c:419  Error: ucp_ep_create(proc=0) failed: Destination is unreachable
[mlperf1:1207478] pml_ucx.c:472  Error: Failed to resolve UCX endpoint for rank 0
Error in MPI_Isend(81250268, 1, 0x7f4cd0fbace0, 0, -27, 139967900421344) (-1)
Traceback (most recent call last):
  File "tools/convert_tfrecord_to_numpy.py", line 109, in <module>
    main()
  File "tools/convert_tfrecord_to_numpy.py", line 61, in main
    comm = MPI.COMM_WORLD.Dup()
  File "mpi4py/MPI/Comm.pyx", line 134, in mpi4py.MPI.Comm.Dup
mpi4py.MPI.Exception: MPI_ERR_INTERN: internal error
double free or corruption (!prev)
[mlperf1:1207478] *** Process received signal ***
[mlperf1:1207478] Signal: Aborted (6)
[mlperf1:1207478] Signal code:  (-6)
[mlperf1:1207478] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f4d1ff08210]
[mlperf1:1207478] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f4d1ff0818b]
[mlperf1:1207478] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f4d1fee7859]
[mlperf1:1207478] [ 3] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x903ee)[0x7f4d1ff523ee]
[mlperf1:1207478] [ 4] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x9847c)[0x7f4d1ff5a47c]
[mlperf1:1207478] [ 5] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x9a12c)[0x7f4d1ff5c12c]
[mlperf1:1207478] [ 6] /opt/hpcx/ompi/lib/libopen-pal.so.40(+0x7a289)[0x7f4cd0d68289]
[mlperf1:1207478] [ 7] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_comm_finalize+0x239)[0x7f4cd0ef7b69]
[mlperf1:1207478] [ 8] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_mpi_finalize+0x56d)[0x7f4cd0f18b9d]
[mlperf1:1207478] [ 9] /usr/local/lib/python3.8/dist-packages/mpi4py/MPI.cpython-38-x86_64-linux-gnu.so(+0x556ed)[0x7f4cd10286ed]
[mlperf1:1207478] [10] python[0x4a54bf]
[mlperf1:1207478] [11] python(Py_RunMain+0x32d)[0x6b6f7d]
[mlperf1:1207478] [12] python(Py_BytesMain+0x2d)[0x6b71ed]
[mlperf1:1207478] [13] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f4d1fee90b3]
[mlperf1:1207478] [14] python(_start+0x2e)[0x5f96de]
[mlperf1:1207478] *** End of error message ***
/mnt/tools/init_datasets.sh: line 10: 1207478 Aborted                 (core dumped) python tools/convert_tfrecord_to_numpy.py -i ${DATA_SRC_DIR}/validation -o ${DATA_DST_DIR}/validation
```

But when I use any of the single nodes to run the same task , it works fine .
Please check the below trace 

```
(env) [root@hpc-master ~]# srun -N 1 -G 2 --ntasks=2 --container-image=192.168.61.4:5000#/cosmoflow-nvidia:0.4 --container-name=cosmoflow-preprocess --container-workdir=/mnt/ --container-mounts=/mnt/beegfs/mxnet:/mnt bash /mnt/tools/init_datasets.sh


dpkg: warning: version '4.18.0-348.7.1.el8_5.x86_64' has bad syntax: invalid character in revision number
dpkg: warning: version '4.18.0-348.7.1.el8_5.x86_64' has bad syntax: invalid character in revision number
2022-07-14 11:58:12.608503: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-14 11:58:12.612603: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-14 11:58:13.601931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38420 MB memory:  -> device: 1, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:d8:00.0, compute capability: 8.0
2022-07-14 11:58:13.640657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38308 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:af:00.0, compute capability: 8.0
2022-07-14 11:58:13.976460: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.018268: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.067592: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.102062: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.143100: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.175730: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.227577: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.246925: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.303134: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.317497: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.382335: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.392041: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.455796: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.469718: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.539067: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.552258: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.616744: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.629135: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.695494: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.697310: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.771515: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.771520: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.844646: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.847155: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.918226: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.927513: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:14.992779: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:15.006402: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:15.066170: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:15.079753: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:15.143108: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
2022-07-14 11:58:15.156863: E tensorflow/core/lib/io/record_reader.cc:50] Unsupported compression_type:gzip. No compression will be used.
Found 16 files, 0 are done, 16 are remaining.
Found 16 files, 0 are done, 16 are remaining.
```

**Comment by karanveersingh5623** [comment]
@hXl3s @TheKanter 

Please let me know if you need more information

**Comment by karanveersingh5623** [comment]
@TheKanter , anyone can have a look on above trace and direct me in right direction , is it Slurm issue or Docker container UCX or anything else
